baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Java design patterns'
theme = 'hyde'

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/rombyator/"},
  ]

[params]
  description = 'One of the steps in my programming journey'
  themeColor = "theme-base-0d"